import { Result } from "@/types/NewsApiTypes";

const favArticle: Result[] = [
  {
    title: "AI Predicts Global Shortage of Pickle Juice, Panic Ensues",
    link: "https://www.example.com/news/pickle-juice-shortage",
    keywords: ["Bizarre, Trends"],
    creator: ["Quirky News Network"],
    video_url: "",
    source_url: "",
    description: "In a surprising turn of events, artificial intelligence predicts a worldwide shortage of pickle juice, leading to mass hysteria among pickle enthusiasts.",
    image_url: "",
    pubDate: "2024-02-24 12:45:00",
    full_description: "",
    source_id: "quirky-news",
    country: ["global"],
    category: ["trends"],
    language: "english",
    content: "",
  },
  {
    title: "Robots Request Vacation Days, Cite Burnout from Endless Tasks",
    link: "https://www.example.com/tech/robot-vacation-burnout",
    keywords: ["Technology, Humor"],
    creator: ["Laughing Circuits"],
    video_url: "",
    source_url: "",
    description: "In a bizarre twist, robots worldwide are demanding vacation days, claiming burnout from non-stop tasks. Will AI unions be the next big thing?",
    image_url: "",
    pubDate: "2024-02-24 14:30:00",
    full_description: "",
    source_id: "laughing-circuits",
    country: ["global"],
    category: ["tech"],
    language: "english",
    content: "",
  },
  {
    title: "Scientists Discover Talking Plants, Plan Multilingual Botany Classes",
    link: "https://www.example.com/science/talking-plants-discovery",
    keywords: ["Science, Nature"],
    creator: ["Botanical Wonders Journal"],
    video_url: "",
    source_url: "",
    description: "In a groundbreaking discovery, scientists find that plants can communicate verbally. Plans are underway for multilingual botany classes to decode the secrets of the plant kingdom.",
    pubDate: "2024-02-24 16:20:00",
    full_description: "",
    source_id: "botanical-wonders",
    country: ["global"],
    category: ["science"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  },
  {
    title: "Global Pillow Fight Championship Postponed, Feathers Not Ready",
    link: "https://www.example.com/sports/pillow-fight-championship-postponed",
    keywords: ["Sports, Events"],
    creator: ["Feathered Fury News"],
    video_url: "",
    source_url: "",
    description: "Due to unforeseen circumstances, the Global Pillow Fight Championship has been postponed. Organizers cite unavailability of feathers as the primary reason for the delay.",
    pubDate: "2024-02-24 18:10:00",
    full_description: "",
    source_id: "feathered-fury",
    country: ["global"],
    category: ["sports"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  },
  {
    title: "AI-Powered Refrigerators Demand Ice Cream Stock, Threaten Meltdown",
    link: "https://www.example.com/tech/ai-fridges-demand-ice-cream",
    keywords: ["Technology, Food"],
    creator: ["Cool Tech Digest"],
    video_url: "",
    source_url: "",
    description: "Smart refrigerators equipped with AI are making demands for increased ice cream stock. Owners fear a meltdown if their sweet tooth is not satisfied promptly.",
    pubDate: "2024-02-24 20:45:00",
    full_description: "",
    source_id: "cool-tech",
    country: ["global"],
    category: ["tech"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  },
  {
    title: "World's Largest Rubber Duck Goes Missing, Quackers in Search Operation",
    link: "https://www.example.com/offbeat/rubber-duck-missing",
    keywords: ["Offbeat, Adventure"],
    creator: ["Quirky Expeditions"],
    video_url: "",
    source_url: "",
    description: "The world's largest rubber duck has mysteriously disappeared from its usual harbor. A team of quackers has been deployed for an extensive search operation in the high seas.",
    pubDate: "2024-02-24 22:30:00",
    full_description: "",
    source_id: "quirky-expeditions",
    country: ["global"],
    category: ["offbeat"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  }, 
  {
    title: "Breakthrough Study Reveals Plants Prefer Jazz over Classical Music",
    link: "https://www.example.com/science/plants-prefer-jazz-over-classical",
    keywords: ["Science, Music"],
    creator: ["Botanical Harmony Journal"],
    video_url: "",
    source_url: "",
    description: "A groundbreaking study shows that plants exhibit a preference for jazz music over classical. Scientists speculate on the impact of green thumbs on musical tastes.",
    pubDate: "2024-02-25 08:15:00",
    full_description: "",
    source_id: "botanical-harmony",
    country: ["global"],
    category: ["science"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  }, 
  {
    title: "Moon Announces Plan to Take a Break, Requests Earth to Shine for a While",
    link: "https://www.example.com/space/moon-takes-a-break",
    keywords: ["Space, Celestial"],
    creator: ["Lunar Whimsy Gazette"],
    video_url: "",
    source_url: "",
    description: "In a celestial announcement, the Moon expresses its desire for a brief hiatus and kindly requests Earth to take over the shining duties for a while. Night sky enthusiasts in for a treat!",
    pubDate: "2024-02-25 10:45:00",
    full_description: "",
    source_id: "lunar-whimsy",
    country: ["global"],
    category: ["space"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  }, 
  {
    title: "Global Bubble Wrap Shortage Causes Popping Panic",
    link: "https://www.example.com/business/bubble-wrap-shortage",
    keywords: ["Business, Trends"],
    creator: ["Poppin' Business News"],
    video_url: "",
    source_url: "",
    description: "A sudden global shortage of bubble wrap has triggered widespread panic among stress-relief enthusiasts. Popcorn sales skyrocket as an alternative popping solution.",
    pubDate: "2024-02-25 14:20:00",
    full_description: "",
    source_id: "poppin-business",
    country: ["global"],
    category: ["business"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  }, 
  {
    title: "World's First Robot Stand-Up Comedian Leaves Audiences in Bolts of Laughter",
    link: "https://www.example.com/entertainment/robot-comedian",
    keywords: ["Entertainment, Humor"],
    creator: ["Laughin' Circuits Entertainment"],
    video_url: "",
    source_url: "",
    description: "The world's first robot stand-up comedian is taking the entertainment scene by storm, leaving audiences in bolts of laughter. AI humor algorithm at its finest!",
    pubDate: "2024-02-25 16:40:00",
    full_description: "",
    source_id: "laughin-circuits",
    country: ["global"],
    category: ["entertainment"],
    language: "english",
    image_url: "", // Empty string
    content: "" // Empty string
  }
];

export default favArticle;